apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: ns-datalake #FIXME: namespace
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: ns-datalake #FIXME: namespace
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:16.2-alpine3.19
        name: postgresql
        env:
        - name: POSTGRES_PASSWORD
          value: psqlpasswrod #FIXME: name
        - name: POSTGRES_DB
          value: metastore #FIXME: name
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgresql-storage
        ports:
        - containerPort: 5432
          name: psql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: psql-pvc
