apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ns-datalake #FIXME: namespace
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi