apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
  namespace: ns-datalake #FIXME: namespace
spec:
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      containers:
      - name: aws-cli
        image: amazon/aws-cli:2.13.2
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity;"]
        env:
          - name: AWS_ACCESS_KEY_ID
            value: myminio
          - name: AWS_SECRET_ACCESS_KEY
            value: myminio123
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: S3_SIGNATURE_VERSION
            value: s3v4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9999
