---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ns-datalake #FIXME: namespace
  name: hive-warehouse-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
